name: TelegramChat17
main: de.Linus122.TelegramChat.Main
version: 1.1
authors: [Linus122, JPSheehan]
description: Brings minecraft chat to Telegram!
commands:
   telegram:
      description: Main command
      usage: /<command> [token]
      permission: telegram.settoken
   linktelegram:
      description: Main command
      usage: /<command>
      permission: telegram.linktelegram